// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Continent documents */
interface ContinentDocumentData {
    /**
     * Title field in *Continent*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Continent*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: continent.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ContinentDocumentDataSlicesSlice>;
}
/**
 * Slice for *Continent → Slice Zone*
 *
 */
type ContinentDocumentDataSlicesSlice = HeaderSlice | ContinentBannerSlice | ContinentContentSlice | CitiesSlice;
/**
 * Continent document from Prismic
 *
 * - **API ID**: `continent`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContinentDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ContinentDocumentData>, "continent", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HeaderSlice | HeroSlice | FeaturesSlice | SeparatorSlice | CallToActionSlice | SliderSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = ContinentDocument | PageDocument;
/**
 * Primary content in CallToAction → Primary
 *
 */
interface CallToActionSliceDefaultPrimary {
    /**
     * Texto field in *CallToAction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: call_to_action.primary.callToActionText
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    callToActionText: prismicT.RichTextField;
}
/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CallToAction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CallToActionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CallToActionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CallToAction*
 *
 */
type CallToActionSliceVariation = CallToActionSliceDefault;
/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: `CallToAction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CallToActionSlice = prismicT.SharedSlice<"call_to_action", CallToActionSliceVariation>;
/**
 * Primary content in Cities → Primary
 *
 */
interface CitiesSliceDefaultPrimary {
    /**
     * Title field in *Cities → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cities.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in Cities → Items
 *
 */
export interface CitiesSliceDefaultItem {
    /**
     * City image field in *Cities → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cities.items[].cityImage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cityImage: prismicT.ImageField<never>;
    /**
     * City Name field in *Cities → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cities.items[].cityName
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cityName: prismicT.KeyTextField;
    /**
     * State Name field in *Cities → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cities.items[].stateName
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    stateName: prismicT.KeyTextField;
    /**
     * State Flag field in *Cities → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cities.items[].stateFlag
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    stateFlag: prismicT.ImageField<never>;
}
/**
 * Default variation for Cities Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Cities`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CitiesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CitiesSliceDefaultPrimary>, Simplify<CitiesSliceDefaultItem>>;
/**
 * Slice variation for *Cities*
 *
 */
type CitiesSliceVariation = CitiesSliceDefault;
/**
 * Cities Shared Slice
 *
 * - **API ID**: `cities`
 * - **Description**: `Cities`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CitiesSlice = prismicT.SharedSlice<"cities", CitiesSliceVariation>;
/**
 * Primary content in ContinentBanner → Primary
 *
 */
interface ContinentBannerSliceDefaultPrimary {
    /**
     * Continente field in *ContinentBanner → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent_banner.primary.continent
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    continent: prismicT.KeyTextField;
    /**
     * Banner field in *ContinentBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: continent_banner.primary.bannerContinent
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    bannerContinent: prismicT.ImageField<never>;
}
/**
 * Default variation for ContinentBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ContinentBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContinentBannerSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ContinentBannerSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ContinentBanner*
 *
 */
type ContinentBannerSliceVariation = ContinentBannerSliceDefault;
/**
 * ContinentBanner Shared Slice
 *
 * - **API ID**: `continent_banner`
 * - **Description**: `ContinentBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContinentBannerSlice = prismicT.SharedSlice<"continent_banner", ContinentBannerSliceVariation>;
/**
 * Primary content in ContinentContent → Primary
 *
 */
interface ContinentContentSliceDefaultPrimary {
    /**
     * Bio field in *ContinentContent → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: continent_content.primary.continentBio
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    continentBio: prismicT.RichTextField;
}
/**
 * Item in ContinentContent → Items
 *
 */
export interface ContinentContentSliceDefaultItem {
    /**
     * Number Item field in *ContinentContent → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: continent_content.items[].numberItem
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    numberItem: prismicT.NumberField;
    /**
     * Item field in *ContinentContent → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: continent_content.items[].continentItem
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    continentItem: prismicT.KeyTextField;
    /**
     * hasInfo field in *ContinentContent → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: continent_content.items[].hasinfo
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    hasinfo: prismicT.BooleanField;
}
/**
 * Default variation for ContinentContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ContinentContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContinentContentSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ContinentContentSliceDefaultPrimary>, Simplify<ContinentContentSliceDefaultItem>>;
/**
 * Slice variation for *ContinentContent*
 *
 */
type ContinentContentSliceVariation = ContinentContentSliceDefault;
/**
 * ContinentContent Shared Slice
 *
 * - **API ID**: `continent_content`
 * - **Description**: `ContinentContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContinentContentSlice = prismicT.SharedSlice<"continent_content", ContinentContentSliceVariation>;
/**
 * Item in Features → Items
 *
 */
export interface FeaturesSliceDefaultItem {
    /**
     * Icone field in *Features → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: features.items[].featureIcon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    featureIcon: prismicT.ImageField<never>;
    /**
     * text field in *Features → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
}
/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<FeaturesSliceDefaultItem>>;
/**
 * Slice variation for *Features*
 *
 */
type FeaturesSliceVariation = FeaturesSliceDefault;
/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: `Features`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSlice = prismicT.SharedSlice<"features", FeaturesSliceVariation>;
/**
 * Primary content in Header → Primary
 *
 */
interface HeaderSliceDefaultPrimary {
    /**
     * Logo field in *Header → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeaderSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Header*
 *
 */
type HeaderSliceVariation = HeaderSliceDefault;
/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSlice = prismicT.SharedSlice<"header", HeaderSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Title field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Text field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
    /**
     * Background Image field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.backgroundImage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    backgroundImage: prismicT.ImageField<never>;
    /**
     * Banner Icon field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.bannerIcon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    bannerIcon: prismicT.ImageField<never>;
    /**
     * Icon Side field in *Hero → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.iconSide
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    iconSide: prismicT.SelectField<"Left" | "Right">;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in Separator → Primary
 *
 */
interface SeparatorSliceDefaultPrimary {
    /**
     * Separador  field in *Separator → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: separator.primary.isSeparator
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    isSeparator: prismicT.BooleanField;
}
/**
 * Default variation for Separator Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Separator`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SeparatorSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SeparatorSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Separator*
 *
 */
type SeparatorSliceVariation = SeparatorSliceDefault;
/**
 * Separator Shared Slice
 *
 * - **API ID**: `separator`
 * - **Description**: `Separator`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SeparatorSlice = prismicT.SharedSlice<"separator", SeparatorSliceVariation>;
/**
 * Item in Slider → Items
 *
 */
export interface SliderSliceDefaultItem {
    /**
     * Continent ID field in *Slider → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: slider.items[].continentId
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    continentId: prismicT.KeyTextField;
    /**
     * Banner field in *Slider → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: slider.items[].banner
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    banner: prismicT.ImageField<never>;
    /**
     * Continent field in *Slider → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: slider.items[].continent
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    continent: prismicT.KeyTextField;
    /**
     * Description field in *Slider → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: slider.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Slider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SliderSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<SliderSliceDefaultItem>>;
/**
 * Slice variation for *Slider*
 *
 */
type SliderSliceVariation = SliderSliceDefault;
/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: `Slider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SliderSlice = prismicT.SharedSlice<"slider", SliderSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ContinentDocumentData, ContinentDocumentDataSlicesSlice, ContinentDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, CallToActionSliceDefaultPrimary, CallToActionSliceDefault, CallToActionSliceVariation, CallToActionSlice, CitiesSliceDefaultPrimary, CitiesSliceDefaultItem, CitiesSliceDefault, CitiesSliceVariation, CitiesSlice, ContinentBannerSliceDefaultPrimary, ContinentBannerSliceDefault, ContinentBannerSliceVariation, ContinentBannerSlice, ContinentContentSliceDefaultPrimary, ContinentContentSliceDefaultItem, ContinentContentSliceDefault, ContinentContentSliceVariation, ContinentContentSlice, FeaturesSliceDefaultItem, FeaturesSliceDefault, FeaturesSliceVariation, FeaturesSlice, HeaderSliceDefaultPrimary, HeaderSliceDefault, HeaderSliceVariation, HeaderSlice, HeroSliceDefaultPrimary, HeroSliceDefault, HeroSliceVariation, HeroSlice, SeparatorSliceDefaultPrimary, SeparatorSliceDefault, SeparatorSliceVariation, SeparatorSlice, SliderSliceDefaultItem, SliderSliceDefault, SliderSliceVariation, SliderSlice };
    }
}
