// Code generated by Slice Machine. DO NOT EDIT.

import Features from './Features';
import Header from './Header';
import Hero from './Hero';

export {
	Features,
	Header,
	Hero,
};

export const components = {
	features: Features,
	header: Header,
	hero: Hero,
};
