// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Features from './Features';
import Header from './Header';
import Hero from './Hero';
import Separator from './Separator';
import Slider from './Slider';

export {
	CallToAction,
	Features,
	Header,
	Hero,
	Separator,
	Slider,
};

export const components = {
	call_to_action: CallToAction,
	features: Features,
	header: Header,
	hero: Hero,
	separator: Separator,
	slider: Slider,
};
