// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Cities from './Cities';
import ContinentBanner from './ContinentBanner';
import ContinentContent from './ContinentContent';
import Features from './Features';
import Header from './Header';
import Hero from './Hero';
import Separator from './Separator';
import Slider from './Slider';

export {
	CallToAction,
	Cities,
	ContinentBanner,
	ContinentContent,
	Features,
	Header,
	Hero,
	Separator,
	Slider,
};

export const components = {
	call_to_action: CallToAction,
	cities: Cities,
	continent_banner: ContinentBanner,
	continent_content: ContinentContent,
	features: Features,
	header: Header,
	hero: Hero,
	separator: Separator,
	slider: Slider,
};
